# -*- coding: utf-8 -*-
"""analyses_lexical_with_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eaDdaYUi-4V_KaNiDn6EQeAzmg27iItG
"""

import pandas as pd

from pathlib import Path

import pandas as pd

from filter_data_llama_6 import (
    load_human,
    get_all_models,
)

K_VALUES = [5, 10, 15, 20, 50, 100, 200, 400]

OUT = Path("output/lexical")
OUT.mkdir(parents=True, exist_ok=True)

# ════════════════════════════════════════════════════════════════════
# LOAD HUMAN DATA
# ════════════════════════════════════════════════════════════════════

people = load_human()

# --- Context lookup: target_word -> left_context ---
context_lookup = (
    people.drop_duplicates("word.id")[["word.id", "Left context"]]
    .rename(columns={
        "word.id": "target_word",
        "Left context": "left_context",
    })
)

# ════════════════════════════════════════════════════════════════════
# HUMAN LEXICAL DISTRIBUTIONS (compute once)
# ════════════════════════════════════════════════════════════════════

all_human_answers = []
all_human_lemmas = []

human_lemma_probs = {}
human_lemma_sets = {}

human_surface_probs = {}
human_surface_sets = {}

for word_id, ppl in people.groupby("word.id"):

    left_ctx = context_lookup.loc[
        context_lookup["target_word"] == word_id,
        "left_context"
    ].iloc[0]

    # ------------------------------------------------------------
    # Human lemma probabilities
    # ------------------------------------------------------------

    answer_level = (
        ppl.assign(
            answer_stripped=ppl["answer"].str.strip(),
            lemma_stripped=ppl["lemma_answer"].astype(str).str.strip(),
        )
        .drop_duplicates(subset=["answer_stripped"])
        [["answer_stripped", "lemma_stripped", "probability_y"]]
    )

    # Save human answers
    for _, r in answer_level.iterrows():
        all_human_answers.append({
            "left_context": left_ctx,
            "target_word": word_id,
            "answer": r["answer_stripped"],
            "lemma_answer": r["lemma_stripped"],
            "probability_y": r["probability_y"],
        })

    lemma_prob = (
        answer_level
        .groupby("lemma_stripped")["probability_y"]
        .sum()
        .to_dict()
    )

    human_lemma_probs[word_id] = lemma_prob
    human_lemma_sets[word_id] = set(lemma_prob.keys())

    # Save human lemmas
    for lemma, prob in lemma_prob.items():
        all_human_lemmas.append({
            "left_context": left_ctx,
            "target_word": word_id,
            "lemma": lemma,
            "probability": prob,
        })

    # ------------------------------------------------------------
    # Human surface-form probabilities
    # ------------------------------------------------------------

    answer_prob = (
        ppl.groupby(ppl["answer"].str.strip())["probability_y"]
        .first()
        .to_dict()
    )

    human_surface_probs[word_id] = answer_prob
    human_surface_sets[word_id] = set(answer_prob.keys())

# ════════════════════════════════════════════════════════════════════
# SAVE HUMAN FILES ONCE
# ════════════════════════════════════════════════════════════════════

ha_df = pd.DataFrame(all_human_answers)
ha_df.to_csv(OUT / "human_answers.csv", index=False)
print(f"Written {len(ha_df)} rows to {OUT / 'human_answers.csv'}")

hl_df = pd.DataFrame(all_human_lemmas)
hl_df.to_csv(OUT / "human_lemmas.csv", index=False)
print(f"Written {len(hl_df)} rows to {OUT / 'human_lemmas.csv'}")

# ════════════════════════════════════════════════════════════════════
# LOOP OVER MODELS
# ════════════════════════════════════════════════════════════════════

for model_name, model_df in get_all_models().items():

    print(f"\n\n\n========== {model_name} ==========\n")

    model_slug = model_name.replace(" ", "_").replace("-", "_")

    # ------------------------------------------------------------
    # DEDUP BY LEMMA
    # ------------------------------------------------------------

    model_sorted = model_df.sort_values(
        "probability_converted",
        ascending=False,
    )

    model_lemma_lists = (
        model_sorted
        .drop_duplicates(
            subset=["target_word_id", "lemma_word"],
            keep="first",
        )
        .groupby("target_word_id", sort=False)
        .apply(
            lambda df: df["lemma_word"].tolist(),
            include_groups=False,
        )
        .rename("model_lemmas")
    )

    # ------------------------------------------------------------
    # DEDUP BY SURFACE FORM
    # ------------------------------------------------------------

    model_surface_lists = (
        model_sorted
        .drop_duplicates(
            subset=["target_word_id", "pred_stripped"],
            keep="first",
        )
        .groupby("target_word_id", sort=False)
        .apply(
            lambda df: df["pred_stripped"].tolist(),
            include_groups=False,
        )
        .rename("model_surface")
    )

    # ------------------------------------------------------------
    # MAIN OVERLAP COMPUTATION
    # ------------------------------------------------------------

    records = []

    for word_id, model_lemmas in model_lemma_lists.items():

        left_ctx = context_lookup.loc[
            context_lookup["target_word"] == word_id,
            "left_context"
        ].iloc[0]

        human_lemmas = human_lemma_sets.get(word_id, set())
        lemma_prob = human_lemma_probs.get(word_id, {})

        human_answers = human_surface_sets.get(word_id, set())
        answer_prob = human_surface_probs.get(word_id, {})

        model_surface = model_surface_lists.get(word_id, [])

        row = {
            "target_word": word_id,
            "n_human_lemmas": len(human_lemmas),
        }

        for k in K_VALUES:

            # ====================================================
            # LEMMA OVERLAP
            # ====================================================

            top_k_lemmas = set(model_lemmas[:k])

            found_lemmas = human_lemmas & top_k_lemmas

            row[f"overlap_at_{k}"] = (
                len(found_lemmas) / len(human_lemmas)
                if human_lemmas else 0.0
            )

            row[f"weighted_overlap_at_{k}"] = sum(
                lemma_prob[lem]
                for lem in found_lemmas
            )

            # ====================================================
            # SURFACE MATCH
            # ====================================================

            top_k_surface = set(model_surface[:k])

            found_surface = human_answers & top_k_surface

            row[f"surface_match_at_{k}"] = (
                len(found_surface) / len(human_answers)
                if human_answers else 0.0
            )

            row[f"surface_weighted_match_at_{k}"] = sum(
                answer_prob[a]
                for a in found_surface
            )

        records.append(row)

    # ════════════════════════════════════════════════════════════════
    # SAVE PER-CONTEXT RESULTS
    # ════════════════════════════════════════════════════════════════

    out = pd.DataFrame(records)

    out = out.merge(
        context_lookup,
        left_on="target_word",
        right_on="target_word",
    )

    # Reorder columns
    cols = ["left_context", "target_word"] + [
        c for c in out.columns
        if c not in ("left_context", "target_word")
    ]

    out = out[cols]

    out.to_csv(
        OUT / f"per_context_overlap_{model_slug}.csv",
        index=False,
    )

    print(
        f"Written {len(out)} rows to "
        f"{OUT / f'per_context_overlap_{model_slug}.csv'}"
    )

    # ════════════════════════════════════════════════════════════════
    # SUMMARY
    # ════════════════════════════════════════════════════════════════

    summary_records = []

    for k in K_VALUES:

        summary_records.append({
            "K": k,

            "overlap_at_K":
                out[f"overlap_at_{k}"].mean(),

            "weighted_overlap_at_K":
                out[f"weighted_overlap_at_{k}"].mean(),

            "surface_match_at_K":
                out[f"surface_match_at_{k}"].mean(),

            "surface_weighted_match_at_K":
                out[f"surface_weighted_match_at_{k}"].mean(),
        })

    summary = pd.DataFrame(summary_records)

    summary.to_csv(
        OUT / f"summary_{model_slug}.csv",
        index=False,
    )

    print(
        f"Written {len(summary)} rows to "
        f"{OUT / f'summary_{model_slug}.csv'}"
    )

    # ════════════════════════════════════════════════════════════════
    # PRINT SUMMARY
    # ════════════════════════════════════════════════════════════════

    print(f"\n=== Mean across all contexts [{model_name}] ===\n")

    print(
        f"{'K':>5}  "
        f"{'overlap@K':>12}  "
        f"{'wt_overlap@K':>14}  "
        f"{'surf_match@K':>14}  "
        f"{'wt_surf_match@K':>17}"
    )

    print("-" * 75)

    for k in K_VALUES:

        ov = out[f"overlap_at_{k}"].mean()

        wov = out[f"weighted_overlap_at_{k}"].mean()

        sm = out[f"surface_match_at_{k}"].mean()

        wsm = out[f"surface_weighted_match_at_{k}"].mean()

        print(
            f"{k:>5}  "
            f"{ov:>12.3f}  "
            f"{wov:>14.3f}  "
            f"{sm:>14.3f}  "
            f"{wsm:>17.3f}"
        )