# -*- coding: utf-8 -*-
"""filter_data_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1713XW0qbcJHaah7uMTHb3osg18rkgdVB
"""

import pandas as pd


def load_human(path: str = "people_with_prob.csv") -> pd.DataFrame:
    """Load human cloze data, keep only Russian answers, renormalize probability_y."""
    df = pd.read_csv(path)
    df = df[df["is_russian"] == True].copy()  # noqa: E712

    # Recompute probability_y: within each context, the proportion of
    # respondents who gave each answer (among remaining Russian answers).
    df["probability_y"] = df.groupby("word.id")["answer"].transform(
        lambda s: s.map(s.value_counts(normalize=True))
    )
    return df


def load_gpt(path: str = "gpt4omini_morph_2.csv") -> pd.DataFrame:
    """Load GPT-4o-mini predictions, keep only Russian tokens."""
    df = pd.read_csv(path)
    return df[df["is_russian"] == True].copy()



def load_gpt(path: str = "llama_with_all.csv") -> pd.DataFrame:
    """Load GPT-4o-mini predictions, keep only Russian tokens."""
    df = pd.read_csv(path)
    return df[df["is_russian"] == True].copy()