# -*- coding: utf-8 -*-
"""filter_data_llama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1713XW0qbcJHaah7uMTHb3osg18rkgdVB
"""

import pandas as pd
import ast
 
 
# HUMAN
 
def load_human(path: str = "people_with_prob.csv") -> pd.DataFrame:
    """Load human cloze data, keep only Russian answers, renormalize probability_y."""
    df = pd.read_csv(path)
    df = df[df["is_russian"] == True].copy()  # noqa: E712

    # Recompute probability_y: within each context, the proportion of
    # respondents who gave each answer (among remaining Russian answers).
    df["probability_y"] = df.groupby("word.id")["answer"].transform(
        lambda s: s.map(s.value_counts(normalize=True))
    )
    return df



def _normalize_model_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Приводит датафрейм любой модели к единому интерфейсу:
      - prediction_cleaned    (поверхностная форма)
      - probability_converted (вероятность слова, float)
      - feature_accuracy      (список совпавших признаков)
      - pred_stripped         (strip поверхностной формы)
    """
    rename_map = {}
    if "word" in df.columns and "prediction_cleaned" not in df.columns:
        rename_map["word"] = "prediction_cleaned"
    if "probability" in df.columns and "probability_converted" not in df.columns:
        rename_map["probability"] = "probability_converted"
    if "feature_intersection" in df.columns and "feature_accuracy" not in df.columns:
        rename_map["feature_intersection"] = "feature_accuracy"

    if rename_map:
        df = df.rename(columns=rename_map)

    # гарантируем float — на случай если pandas прочитал как object
    df["probability_converted"] = pd.to_numeric(
        df["probability_converted"], errors="coerce"
    )

    df["pred_stripped"] = df["prediction_cleaned"].str.strip()

    return df


# ════════════════════════════════════════════════════════════════════
# GPT
# ═══════════════════════════════════════════════════════════════════

def load_gpt(path: str = "gpt4omini_morph_2.csv") -> pd.DataFrame:
    """Load GPT-4o-mini predictions, keep only Russian tokens."""
    df = pd.read_csv(path)
    df = df[df["is_russian"] == True].copy()
    return _normalize_model_df(df)


# ════════════════════════════════════════════════════════════════════
# LLAMA
# ════════════════════════════════════════════════════════════════════

def load_llama(path: str = "llama_with_all.csv") -> pd.DataFrame:
    """
    Load Llama predictions, keep only Russian tokens.

    Отличия от GPT, которые фиксируются здесь:
      1. word               → prediction_cleaned
         probability        → probability_converted
         feature_intersection → feature_accuracy
      2. sentence_text содержит ' <mask>' в конце — убираем,
         чтобы не мешало если поле используется как ключ join.
      3. probability читается как object если CSV содержит артефакты
         (np.float16(...)) — ast.literal_eval + pd.to_numeric решает это.
    """
    df = pd.read_csv(path)
    df = df[df["is_russian"] == True].copy()

    # убираем ' <mask>' из sentence_text
    if "sentence_text" in df.columns:
        df["sentence_text"] = (
            df["sentence_text"]
            .str.replace(r"\s*<mask>\s*$", "", regex=True)
            .str.strip()
        )

    # Функция для безопасного преобразования строки в число через ast.literal_eval
    def parse_prob_column(col: pd.Series) -> pd.Series:
        def _parse(x):
            if pd.isna(x):
                return x
            if isinstance(x, (int, float)):
                return float(x)
            try:
                # Пробуем распарсить как Python-литерал (число или строка)
                parsed = ast.literal_eval(str(x))
                # Если получился список/кортеж — берём первый элемент
                if isinstance(parsed, (list, tuple)) and len(parsed) > 0:
                    parsed = parsed[0]
                return float(parsed)
            except (ValueError, SyntaxError, TypeError):
                # Если не парсится — пробуем прямое преобразование
                try:
                    return pd.to_numeric(x, errors="coerce")
                except:
                    return pd.NA
        return col.apply(_parse)

    # Применяем к probability и token_probability, если они есть
    for col in ["probability", "token_probabilities"]:
        if col in df.columns:
            df[col] = parse_prob_column(df[col])

    return _normalize_model_df(df)


# ════════════════════════════════════════════════════════════════════
# УНИВЕРСАЛЬНЫЕ ФУНКЦИИ ДЕДУПЛИКАЦИИ
# ════════════════════════════════════════════════════════════════════

def dedup_by_lemma(model_df: pd.DataFrame) -> pd.Series:
    """target_word_id → список лемм (дедуп по лемме, топ по вероятности)."""
    sorted_df = model_df.sort_values("probability_converted", ascending=False)
    return (
        sorted_df
        .drop_duplicates(subset=["target_word_id", "lemma_word"], keep="first")
        .groupby("target_word_id", sort=False)
        .apply(lambda df: df["lemma_word"].tolist(), include_groups=False)
        .rename("model_lemmas")
    )


def dedup_by_surface(model_df: pd.DataFrame) -> pd.Series:
    """target_word_id → список форм (дедуп по поверхностной форме)."""
    sorted_df = model_df.sort_values("probability_converted", ascending=False)
    return (
        sorted_df
        .drop_duplicates(subset=["target_word_id", "pred_stripped"], keep="first")
        .groupby("target_word_id", sort=False)
        .apply(lambda df: df["pred_stripped"].tolist(), include_groups=False)
        .rename("model_surface")
    )


# ════════════════════════════════════════════════════════════════════
# РЕЕСТР МОДЕЛЕЙ
# ════════════════════════════════════════════════════════════════════

def get_all_models() -> dict:
    """
    Возвращает {model_name: dataframe}.
    Чтобы добавить новую модель — одна строка здесь.
    """
    return {
        "GPT-4o-mini": load_gpt(),
        "Llama":       load_llama(),
    }
 
def _normalize_model_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Приводит датафрейм любой модели к единому интерфейсу:
      - prediction_cleaned   (поверхностная форма)
      - probability_converted (вероятность слова)
      - feature_accuracy      (список совпавших признаков)
      - target_word_id, upos_word, lemma_word, feats,
        target_mapped_POS, target_mapped_feats_ud, is_russian
        — остаются как есть если уже присутствуют
 
    Также добавляет pred_stripped (strip поверхностной формы).
    """
    rename_map = {}
 
    # Llama называет колонки иначе — переименовываем
    if "word" in df.columns and "prediction_cleaned" not in df.columns:
        rename_map["word"] = "prediction_cleaned"
    if "probability" in df.columns and "probability_converted" not in df.columns:
        rename_map["probability"] = "probability_converted"
    if "feature_intersection" in df.columns and "feature_accuracy" not in df.columns:
        rename_map["feature_intersection"] = "feature_accuracy"
 
    if rename_map:
        df = df.rename(columns=rename_map)
 
    # strip поверхностной формы — нужен во многих скриптах
    df["pred_stripped"] = df["prediction_cleaned"].str.strip()
 
    return df
 

# GPT
 
def load_gpt(path: str = "gpt4omini_morph_2.csv") -> pd.DataFrame:
    """Load GPT-4o-mini predictions, keep only Russian tokens."""
    df = pd.read_csv(path)
    df = df[df["is_russian"] == True].copy()
    return _normalize_model_df(df)
 
 

# LLAMA
 
def load_llama(path: str = "llama_with_all.csv") -> pd.DataFrame:
    """
    Load Llama predictions, keep only Russian tokens.
 
    Совместимость с GPT:
      word               → prediction_cleaned
      probability        → probability_converted   (joint prob токенов из beam search)
      feature_intersection → feature_accuracy
 
    Примечание по вероятностям:
      probability = произведение токенных вероятностей (beam search joint prob).
      Природа та же, что у probability_converted в GPT — ненормализованное
      распределение по топ-k словам. Нормализация по контексту не применяется,
      чтобы сохранить сопоставимость с GPT.
    """
    df = pd.read_csv(path)
    df = df[df["is_russian"] == True].copy()
    return _normalize_model_df(df)
 
 

 
def dedup_by_lemma(model_df: pd.DataFrame) -> pd.Series:
    """
    Дедупликация по лемме: для каждого контекста оставляем
    одну запись на уникальную лемму (с наибольшей вероятностью).
    Возвращает Series: target_word_id → список лемм.
 
    Использование:
        gpt_deduped = dedup_by_lemma(gpt)
        llama_deduped = dedup_by_lemma(llama)
    """
    sorted_df = model_df.sort_values("probability_converted", ascending=False)
    return (
        sorted_df
        .drop_duplicates(subset=["target_word_id", "lemma_word"], keep="first")
        .groupby("target_word_id", sort=False)
        .apply(lambda df: df["lemma_word"].tolist(), include_groups=False)
        .rename("model_lemmas")
    )
 
 
def dedup_by_surface(model_df: pd.DataFrame) -> pd.Series:
    """
    Дедупликация по поверхностной форме (stripped).
    Возвращает Series: target_word_id → список форм.
    """
    sorted_df = model_df.sort_values("probability_converted", ascending=False)
    return (
        sorted_df
        .drop_duplicates(subset=["target_word_id", "pred_stripped"], keep="first")
        .groupby("target_word_id", sort=False)
        .apply(lambda df: df["pred_stripped"].tolist(), include_groups=False)
        .rename("model_surface")
    )
 
 

def get_all_models() -> dict:
    """
    Возвращает словарь {model_name: dataframe} для всех доступных моделей.
    Чтобы добавить новую модель — достаточно добавить одну строку здесь.
 
    Использование в скриптах анализа:
        from filter_data import load_human, get_all_models
        human = load_human()
        for model_name, model_df in get_all_models().items():
            # ... существующий код анализа ...
    """
    return {
        "GPT-4o-mini": load_gpt(),
        "Llama":       load_llama(),
    }
